wip: Add Octave support
martin-danelljan/ECO pull request #5
Opened 2017-07-01 08:45 UTC by cybertk

This PR brings GNU/Octave support

Changes:

- Add `implmentation/octave_support` dir for all Octave related works.
    - **is_octave.m**, check if running in Octave
    - **gather.m**, Octave dummy implementation of Matlab Parallel Toolbox gather()
- Add a new parameter `is_octave` into  `benchmark_tracker_wrapper()`
- Replace `cast(x, 'like', y)` to `cast(x, class(y))`, Octave does not support 'like' in `cast()`
- Disable `alpha()` when display `bbox` in **demo_ECO** script

2017-07-04 13:12 UTC, martin-danelljan requested changes
Nice work adding Octave support :)
I just have some minor comments.

2017-07-04 13:12 UTC, martin-danelljan commented on implementation/fourier_tools/cfft2.m
> +data_type_complex = complex(zeros(1, class(x)));
I guess this is not needed anymore.

2017-07-04 13:12 UTC, martin-danelljan commented on implementation/tracker.m
> +        samplesf{k} = complex(zeros(filter_sz(k,1),(filter_sz(k,2)+1)/2,sample_dim(k),params.nSamples))
Need to add `class(params.data_type)` .

2017-07-04 13:12 UTC, martin-danelljan commented on implementation/tracker.m
> +        samplesf{k} = complex(zeros(params.nSamples,sample_dim(k),filter_sz(k,1),(filter_sz(k,2)+1)/2), 0);
Need to add `class(params.data_type)`. The second argument in complex can be removed.

2017-07-04 13:12 UTC, martin-danelljan commented on implementation/tracker.m
> +                hf{1,1,k} = complex(zeros([filter_sz(k,1) (filter_sz(k,2)+1)/2 sample_dim(k)]));
Need to add `class(params.data_type)`.

2017-07-04 13:12 UTC, martin-danelljan commented on implementation/tracker.m
> +% yf_y and yf_x, is 1x1x2 cell with vector
1 x 1 x num_feature_blocks

2017-07-04 13:12 UTC, martin-danelljan commented on implementation/tracker.m
> +cos_window = cellfun(@(cos_window) cast(cos_window(2:end-1,2:end-1), 'single'), cos_window, 'uniformoutput', false);
Use the `class(params.data_type)` here as well for consistency.

2017-07-04 13:12 UTC, martin-danelljan commented on README.md
> +1. Start Matlab/Octave and navigate to the repository path, run the install script:
Numbering of bullets is 1., 2., 3.

2017-07-07 05:54 UTC, cybertk commented on implementation/tracker.m
> +                hf{1,1,k} = complex(zeros([filter_sz(k,1) (filter_sz(k,2)+1)/2 sample_dim(k)]));
1. `zeros(N, 'like', complex_data)` will return a **complex** matrix
1. `zeros(N, class(complex_data))` will return a **real** matrix
1. `complex(zeros(N, class(complex_data)))` is what we want(same as 1/)

```
>> N=2;
>> complex_data=complex(zeros(N, 'single'));
>>
>> zeros(N, 'like', complex_data)
ans =
  2×2 single matrix
   0.0000 + 0.0000i   0.0000 + 0.0000i
   0.0000 + 0.0000i   0.0000 + 0.0000i

>> zeros(N, class(complex_data))
ans =
  2×2 single matrix
     0     0
     0     0

>> complex(zeros(N, class(complex_data)))
ans =
  2×2 single matrix
   0.0000 + 0.0000i   0.0000 + 0.0000i
   0.0000 + 0.0000i   0.0000 + 0.0000i
```

2017-07-07 05:56 UTC, cybertk commented on README.md
> +1. Start Matlab/Octave and navigate to the repository path, run the install script:
Just FYI. Markdown supports use same **1.** to create an [order list](https://guides.github.com/features/mastering-markdown/#)

I will still change to 1. 2. 3. as you wish.

2017-07-07 05:58 UTC, cybertk commented on implementation/tracker.m
> +        samplesf{k} = complex(zeros(filter_sz(k,1),(filter_sz(k,2)+1)/2,sample_dim(k),params.nSamples))
1. `zeros(N, 'like', complex_data)` will return a **complex** matrix
1. `zeros(N, class(complex_data))` will return a **real** matrix
1. `complex(zeros(N, class(complex_data)))` is what we want(same as 1/)

```
>> N=2;
>> complex_data=complex(zeros(N, 'single'));
>>
>> zeros(N, 'like', complex_data)
ans =
  2×2 single matrix
   0.0000 + 0.0000i   0.0000 + 0.0000i
   0.0000 + 0.0000i   0.0000 + 0.0000i

>> zeros(N, class(complex_data))
ans =
  2×2 single matrix
     0     0
     0     0

>> complex(zeros(N, class(complex_data)))
ans =
  2×2 single matrix
   0.0000 + 0.0000i   0.0000 + 0.0000i
   0.0000 + 0.0000i   0.0000 + 0.0000i
```

2017-07-07 05:59 UTC, cybertk commented on implementation/tracker.m
> +cos_window = cellfun(@(cos_window) cast(cos_window(2:end-1,2:end-1), 'single'), cos_window, 'uniformoutput', false);
missed

2017-07-07 06:01 UTC, martin-danelljan commented on implementation/tracker.m
> +                hf{1,1,k} = complex(zeros([filter_sz(k,1) (filter_sz(k,2)+1)/2 sample_dim(k)]));
Yes. I meant we can use 
complex(zeros(... , class(params.data_type)));

2017-07-07 06:02 UTC, martin-danelljan commented on README.md
> +1. Start Matlab/Octave and navigate to the repository path, run the install script:
Ok, then it's fine I guess :)

2017-07-07 06:06 UTC, martin-danelljan commented on implementation/tracker.m
> +        samplesf{k} = complex(zeros(filter_sz(k,1),(filter_sz(k,2)+1)/2,sample_dim(k),params.nSamples))
Yes. I meant we can use
`complex(zeros(... , class(params.data_type)));`

2017-07-07 06:29 UTC, cybertk commented on implementation/tracker.m
> +                hf{1,1,k} = complex(zeros([filter_sz(k,1) (filter_sz(k,2)+1)/2 sample_dim(k)]));
fixed

2017-07-07 09:49 UTC, cybertk commented on implementation/fourier_tools/cfft2.m
> +data_type_complex = complex(zeros(1, class(x)));
ditto

2017-07-08 03:43 UTC, merged

2017-07-08 04:08 UTC, martin-danelljan commented
I had to temporarily revert the pr since I found that the 'cast(...)' does not work properly with gpuArray. We have to think of a solution for this.

2017-07-10 02:38 UTC, cybertk commented
I was only tested the **HC** version of ECO, as **Octave** has no support of GPU. What about if we enable only **ECO_HC**/`params.use_gpu = false` for Octave, and report a warning if not.

2017-07-11 21:44 UTC, martin-danelljan commented
The problem is not that. Since the GPU version run the same code, the allocation and casting operations need to support gpuArray as well. An ugly fix is of course to add
`if is_octave
    ...
else
    ...
end`
around each allocation or casting operation.
Another possibility is to add a separate branch for octave support to keep the code cleaner.

2017-07-12 05:16 UTC, cybertk commented
If we provide a customization version of `cast()` to override system's? In that, we can do `if is_octave ... else ... end`. 

Is it acceptable?

But I thinks we can try to fix the real root-cause. I'm not sure I understand the issue,`cast(A, class(B))` does not work if `A/B` is `gpuArray`?

2017-07-12 05:19 UTC, cybertk commented
Actually, I'm trying to encapsulate ECO with a thin C/C++ wrapper with **liboctave**. Then we can integrate it into production code. So the Octave support is the first step of that.

2017-07-12 07:07 UTC, martin-danelljan commented
Sound like a nice idea to integrate it with liboctave.

The problem is essentially  that `class(gpuArray(0))` only returns `'gpuArray'`, but not the precision of it, i.e. single or double. This causes `cast` to simply fail and `zeros` allocates a `gpuArray` of type `double`.

There is also another problem: `complex(zeros(...))` is much slower than the `zeros(..., 'like', data_type_complex)`.

2017-07-12 07:30 UTC, martin-danelljan commented
I thought about some different options. I think the best option is to write custom versions of `zeros` and `cast`, as you say. The downside is that there is a small overhead for such function calls in Matlab.

I have written one for zeros below. It should be called as:
`zeros_like(..., 'like', params.data_type, params.is_octave)`
So, only the `is_octave` needs to be added as a last argument. The `cast_like` function could be implemented in a similar way.

```matlab
function x = zeros_like(varargin)

if varargin{end}
    % Octave
    if isreal(varargin{end-1})
        x = zeros(varargin{1:end-3}, class(varargin{end-1}));
    else
        x = complex(zeros(varargin{1:end-3}, class(varargin{end-1})));
    end
else
    % Matlab
    x = zeros(varargin{1:end-1});
end
end
```

2017-07-12 07:35 UTC, martin-danelljan commented
Or maybe `is_octave` can be added as a persistent variable in the zeros_like function. Then it does not even have to be supplied as a parameter.

2017-07-12 07:40 UTC, cybertk commented
I think `is_octave` should be persistent respected to performance concern